# Noctis Viola

[mgr]
cwd = { fg = "#49d6e9" }
find_keyword = { fg = "#e4b781", bold = true }
find_position = { fg = "#49d6e9", italic = true }
symlink_target = { fg = "#7f659a", italic = true }
marker_copied = { fg = "#49e9a6", bg = "#49e9a6" }
marker_cut = { fg = "#e66533", bg = "#e66533" }
marker_marked = { fg = "#df769b", bg = "#df769b" }
marker_selected = { fg = "#49d6e9", bg = "#49d6e9" }
count_copied = { fg = "#30243d", bg = "#49e9a6" }
count_cut = { fg = "#30243d", bg = "#e66533" }
count_selected = { fg = "#30243d", bg = "#49d6e9" }
border_style = { fg = "#52465f" }

[tabs]
active = { fg = "#ccbfd9", bg = "#392d46" }
inactive = { fg = "#7f659a", bg = "#22192b" }

[mode]
normal_main = { fg = "#30243d", bg = "#49d6e9", bold = true }
normal_alt = { fg = "#49d6e9", bg = "#392d46" }
select_main = { fg = "#30243d", bg = "#df769b", bold = true }
select_alt = { fg = "#df769b", bg = "#392d46" }
unset_main = { fg = "#30243d", bg = "#e798b3", bold = true }
unset_alt = { fg = "#e798b3", bg = "#392d46" }

[indicator]
parent = { bg = "#392d46" }
current = { bg = "#3e3352" }
preview = { bg = "#392d46" }

[status]
overall = { fg = "#ccbfd9", bg = "#392d46" }
perm_sep = { fg = "#52465f" }
perm_type = { fg = "#60dbeb" }
perm_read = { fg = "#e4b781" }
perm_write = { fg = "#e798b3" }
perm_exec = { fg = "#49e9a6" }
progress_label = { fg = "#ccbfd9", bold = true }
progress_normal = { fg = "#49d6e9", bg = "#392d46" }
progress_error = { fg = "#30243d", bg = "#e66533" }

[which]
mask = { bg = "#22192b" }
cand = { fg = "#49d6e9" }
rest = { fg = "#7f659a" }
desc = { fg = "#9589a2" }
separator_style = { fg = "#52465f" }

[confirm]
border = { fg = "#49d6e9" }
title = { fg = "#49d6e9" }
body = { fg = "#ccbfd9" }
list = { fg = "#9589a2" }
btn_yes = { fg = "#30243d", bg = "#49d6e9", bold = true }
btn_no = { fg = "#9589a2" }

[spot]
border = { fg = "#49d6e9" }
title = { fg = "#49d6e9" }
tbl_col = { fg = "#60dbeb" }
tbl_cell = { fg = "#30243d", bg = "#49d6e9" }

[notify]
title_info = { fg = "#49ace9" }
title_warn = { fg = "#e4b781" }
title_error = { fg = "#e66533" }

[pick]
border = { fg = "#49d6e9" }
active = { fg = "#49d6e9", bold = true }
inactive = { fg = "#9589a2" }

[input]
border = { fg = "#49d6e9" }
title = { fg = "#49d6e9" }
value = { fg = "#ccbfd9" }
selected = { bg = "#3e3352" }

[cmp]
border = { fg = "#49d6e9" }
active = { fg = "#30243d", bg = "#49d6e9" }
inactive = { fg = "#9589a2" }

[tasks]
border = { fg = "#49d6e9" }
title = { fg = "#49d6e9" }
hovered = { fg = "#49d6e9", bold = true }

[help]
on = { fg = "#49d6e9" }
run = { fg = "#9589a2" }
desc = { fg = "#7f659a" }
hovered = { bg = "#3e3352", bold = true }
footer = { fg = "#7f659a", bg = "#22192b" }

[filetype]
rules = [
  { url = "*/", fg = "#49d6e9", bold = true },
  { mime = "image/*", fg = "#e69533" },
  { mime = "video/*", fg = "#e4b781" },
  { mime = "audio/*", fg = "#e4b781" },
  { mime = "application/zip", fg = "#df769b" },
  { mime = "application/gzip", fg = "#df769b" },
  { mime = "application/x-tar", fg = "#df769b" },
  { mime = "application/x-bzip2", fg = "#df769b" },
  { mime = "application/x-7z-compressed", fg = "#df769b" },
  { mime = "application/x-rar", fg = "#df769b" },
  { url = "*.rs", fg = "#e69533" },
  { url = "*.lua", fg = "#49d6e9" },
  { url = "*.ts", fg = "#49d6e9" },
  { url = "*.js", fg = "#e4b781" },
  { url = "*.py", fg = "#49e9a6" },
  { url = "*.go", fg = "#60dbeb" },
  { url = "*.md", fg = "#9589a2" },
  { url = "*.json", fg = "#e4b781" },
  { url = "*.toml", fg = "#e69533" },
  { url = "*.yaml", fg = "#e798b3" },
  { url = "*.yml", fg = "#e798b3" },
]


# : Icons 
