"$schema" = 'https://starship.rs/config-schema.json'

# ╭─  dotfiles  main ⇣1⇡2 +1 !2 ───────────────────── 󱦟 3s  12:34
# ╰─❯

format = """
[╭─](dimmed white)\
$directory\
$git_branch\
$git_state\
$git_status\
$fill\
$cmd_duration\
$time\
$line_break\
[╰─](dimmed white)\
$character\
"""

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[fill]
style = "dimmed white"
symbol = "─"

# ─────────────────────────────── Left ────────────────────────────────

[directory]
style = "cyan"
truncation_length = 4
truncate_to_repo = true
read_only = " 󰌾"
read_only_style = "red"
format = "[  $path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
style = "purple"
truncation_length = 32
truncation_symbol = "…"
format = "[on ](dimmed white)[$symbol$branch]($style) "

[git_state]
style = "red"
format = "[\\($state( $progress_current/$progress_total)\\)]($style) "
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
ahead = "[⇡${count} ](yellow)"
behind = "[⇣${count} ](yellow)"
diverged = "[⇣${behind_count}⇡${ahead_count} ](yellow)"
stashed = "[*${count} ](yellow)"
conflicted = "[~${count} ](red)"
staged = "[+${count} ](yellow)"
modified = "[!${count} ](yellow)"
deleted = "[-${count} ](red)"
untracked = "[?${count} ](yellow)"
format = """
(\
$ahead_behind\
$stashed\
$conflicted\
$staged\
$modified\
$deleted\
$untracked\
)\
"""

# ─────────────────────────────── Right ───────────────────────────────

[cmd_duration]
min_time = 3000
style = "dimmed white"
format = "[ 󱦟 $duration]($style)"

[time]
disabled = false
style = "dimmed white"
time_format = "%H:%M"
format = "[  $time]($style)"
