--color=fg:#1f1f1f,bg:#fffbeb,hl:#644ac9
--color=fg+:#000000,bg+:#cfcfde,hl+:#047fb4
--color=border:#cecbbe,header:#644ac9,gutter:#fffbeb
--color=spinner:#644ac9,info:#6c664b
--color=pointer:#644ac9,marker:#14710a,prompt:#a3144d
