--color=fg:#cccac2,bg:#1f2430,hl:#ffcc66
--color=fg+:#e8e7e3,bg+:#2b4768,hl+:#95e6cb
--color=border:#454950,header:#ffcc66,gutter:#1f2430
--color=spinner:#ffcc66,info:#6e7c8f
--color=pointer:#ffcc66,marker:#87d96c,prompt:#dabafa
