--color=fg:#bfbdb6,bg:#0b0e14,hl:#e6b450
--color=fg+:#dcdad7,bg+:#193155,hl+:#95e6cb
--color=border:#333438,header:#e6b450,gutter:#0b0e14
--color=spinner:#e6b450,info:#5a6673
--color=pointer:#e6b450,marker:#7fd962,prompt:#cda1fa
