--color=fg:#5c6166,bg:#f8f9fa,hl:#f29718
--color=fg+:#3f4246,bg+:#d7e4f6,hl+:#4cbf99
--color=border:#d6d8d9,header:#f29718,gutter:#f8f9fa
--color=spinner:#f29718,info:#adaeb1
--color=pointer:#f29718,marker:#6cbf43,prompt:#9e75c7
