--color=fg:#45373c,bg:#d5ccba,hl:#97522c
--color=fg+:#231c1e,bg+:#968c83,hl+:#989a9c
--color=border:#b5ab9e,header:#97522c,gutter:#d5ccba
--color=spinner:#97522c,info:#594d4e
--color=pointer:#97522c,marker:#858162,prompt:#97522c
