--color=fg:#e0dbb7,bg:#2a1f1d,hl:#74a6ad
--color=fg+:#f2f0e2,bg+:#563c27,hl+:#93cfd7
--color=border:#52483f,header:#74a6ad,gutter:#2a1f1d
--color=spinner:#74a6ad,info:#9b6c4a
--color=pointer:#74a6ad,marker:#6ba18a,prompt:#ac80a6
