--color=fg:#f2f4f8,bg:#161616,hl:#33b1ff
--color=fg+:#ffffff,bg+:#f9fbff,hl+:#52bdff
--color=border:#464748,header:#33b1ff,gutter:#161616
--color=spinner:#33b1ff,info:#535353
--color=pointer:#33b1ff,marker:#25be6a,prompt:#be95ff
