--color=fg:#c6d0f5,bg:#303446,hl:#8caaee
--color=fg+:#fafbfe,bg+:#494e63,hl+:#98d2ca
--color=border:#51566c,header:#8caaee,gutter:#303446
--color=spinner:#8caaee,info:#949cbb
--color=pointer:#8caaee,marker:#a6d189,prompt:#f4b8e4
