--color=fg:#cad3f5,bg:#24273a,hl:#8aadf4
--color=fg+:#fefeff,bg+:#404459,hl+:#a5ded6
--color=border:#494d63,header:#8aadf4,gutter:#24273a
--color=spinner:#8aadf4,info:#939ab7
--color=pointer:#8aadf4,marker:#a6da95,prompt:#f5bde6
