--color=fg:#cdd6f4,bg:#1e1e2e,hl:#89b4fa
--color=fg+:#ffffff,bg+:#3b3d4f,hl+:#b1eae1
--color=border:#44465a,header:#89b4fa,gutter:#1e1e2e
--color=spinner:#89b4fa,info:#9399b2
--color=pointer:#89b4fa,marker:#a6e3a1,prompt:#f5c2e7
