--color=fg:#cad3f5,bg:#11111b,hl:#fab387
--color=fg+:#fefeff,bg+:#313244,hl+:#8bd5ca
--color=border:#3a3c4b,header:#fab387,gutter:#11111b
--color=spinner:#fab387,info:#a5adcb
--color=pointer:#fab387,marker:#a6da95,prompt:#c6a0f6
