--color=fg:#575279,bg:#faf4ed,hl:#56949f
--color=fg+:#3c3955,bg+:#4c4769,hl+:#5ca7b4
--color=border:#d6d0d3,header:#56949f,gutter:#faf4ed
--color=spinner:#56949f,info:#bdbfc9
--color=pointer:#56949f,marker:#618774,prompt:#907aa9
