--color=fg:#3d2b5a,bg:#f6f2ee,hl:#287980
--color=fg+:#211731,bg+:#302b5d,hl+:#488d93
--color=border:#cdc6cd,header:#287980,gutter:#f6f2ee
--color=spinner:#287980,info:#aab0ad
--color=pointer:#287980,marker:#396847,prompt:#6e33ce
