--color=fg:#f8f8f2,bg:#282a36,hl:#bd93f9
--color=fg+:#ffffff,bg+:#44475a,hl+:#a4ffff
--color=border:#56575f,header:#bd93f9,gutter:#282a36
--color=spinner:#bd93f9,info:#6272a4
--color=pointer:#bd93f9,marker:#50fa7b,prompt:#ff79c6
