--color=fg:#e0def4,bg:#232136,hl:#65b1cd
--color=fg+:#ffffff,bg+:#433c59,hl+:#a6dae3
--color=border:#4d4b60,header:#65b1cd,gutter:#232136
--color=spinner:#65b1cd,info:#817c9c
--color=pointer:#65b1cd,marker:#a3be8c,prompt:#c4a7e7
