--color=fg:#d8d0c0,bg:#1c1b19,hl:#c8b468
--color=fg+:#efece6,bg+:#3e3c38,hl+:#80a090
--color=border:#45433e,header:#c8b468,gutter:#1c1b19
--color=spinner:#c8b468,info:#706c61
--color=pointer:#c8b468,marker:#8a9868,prompt:#b07878
