--color=fg:#ffcead,bg:#060b1e,hl:#7d82d9
--color=fg+:#fff3ea,bg+:#252e56,hl+:#dfeaf0
--color=border:#3d363d,header:#7d82d9,gutter:#060b1e
--color=spinner:#7d82d9,info:#6d7db6
--color=pointer:#7d82d9,marker:#92a593,prompt:#c89dc1
