--color=fg:#100f0f,bg:#fffcf0,hl:#24837b
--color=fg+:#000000,bg+:#cecdc3,hl+:#3aa99f
--color=border:#cac8bf,header:#24837b,gutter:#fffcf0
--color=spinner:#24837b,info:#b7b5ac
--color=pointer:#24837b,marker:#66800b,prompt:#a02f6f
