--color=fg:#cecdc3,bg:#100f0f,hl:#3aa99f
--color=fg+:#eae9e5,bg+:#403e3c,hl+:#24837b
--color=border:#3a3937,header:#3aa99f,gutter:#100f0f
--color=spinner:#3aa99f,info:#575653
--color=pointer:#3aa99f,marker:#879a39,prompt:#ce5d97
