--color=fg:#242424,bg:#d0d0c8,hl:#de6a41
--color=fg+:#050505,bg+:#dfddeb,hl+:#6b1f2f
--color=border:#aaaaa4,header:#de6a41,gutter:#d0d0c8
--color=spinner:#de6a41,info:#57574c
--color=pointer:#de6a41,marker:#3d6035,prompt:#43432b
