--color=fg:#ddf7ff,bg:#0b0c16,hl:#82fb9c
--color=fg+:#ffffff,bg+:#1f253a,hl+:#d1fffe
--color=border:#394049,header:#82fb9c,gutter:#0b0c16
--color=spinner:#82fb9c,info:#6a6e95
--color=pointer:#82fb9c,marker:#4fe88f,prompt:#86a7df
