--color=fg:#1c2d28,bg:#dfe4c4,hl:#5e81ac
--color=fg+:#050706,bg+:#c8d4a8,hl+:#3d727d
--color=border:#b4bca2,header:#5e81ac,gutter:#dfe4c4
--color=spinner:#5e81ac,info:#727d8a
--color=pointer:#5e81ac,marker:#556753,prompt:#8a5b81
