--color=fg:#efebdc,bg:#1b1b1b,hl:#e75a50
--color=fg+:#ffffff,bg+:#68332f,hl+:#77868a
--color=border:#4a4945,header:#e75a50,gutter:#1b1b1b
--color=spinner:#e75a50,info:#87856d
--color=pointer:#e75a50,marker:#a99b7a,prompt:#9683a1
