--color=fg:#c8c8c8,bg:#13131d,hl:#7c7ca8
--color=fg+:#e7e7e7,bg+:#2c293f,hl+:#d2d7e3
--color=border:#3b3b43,header:#7c7ca8,gutter:#13131d
--color=spinner:#7c7ca8,info:#616177
--color=pointer:#7c7ca8,marker:#a6b2c7,prompt:#9f859f
