--color=fg:#2d2c2a,bg:#f7f3eb,hl:#334a84
--color=fg+:#0d0d0c,bg+:#c9b99a,hl+:#3a6f8c
--color=border:#cbc7c1,header:#334a84,gutter:#f7f3eb
--color=spinner:#334a84,info:#787775
--color=pointer:#334a84,marker:#6d7f59,prompt:#655683
