--color=fg:#e8e8d3,bg:#151515,hl:#7a8aa6
--color=fg+:#fdfdfb,bg+:#404040,hl+:#a0a8b0
--color=border:#43433f,header:#7a8aa6,gutter:#151515
--color=spinner:#7a8aa6,info:#888888
--color=pointer:#7a8aa6,marker:#b39066,prompt:#c7c7c7
