--color=fg:#e8e8d3,bg:#151515,hl:#b0d0f0
--color=fg+:#fdfdfb,bg+:#404040,hl+:#8fbfdc
--color=border:#43433f,header:#b0d0f0,gutter:#151515
--color=spinner:#b0d0f0,info:#888888
--color=pointer:#b0d0f0,marker:#99ad6a,prompt:#c6b6ee
