--color=fg:#dad6c8,bg:#101010,hl:#a6c3d9
--color=fg+:#f3f1ed,bg+:#3c3b38,hl+:#7db7cc
--color=border:#3c3c38,header:#a6c3d9,gutter:#101010
--color=spinner:#a6c3d9,info:#7a7a7a
--color=pointer:#a6c3d9,marker:#909c6e,prompt:#b8aed3
