--color=fg:#000000,bg:#fafafa,hl:#0a3a8a
--color=fg+:#000000,bg+:#e8d0c0,hl+:#0a4a7a
--color=border:#c3c3c3,header:#0a3a8a,gutter:#fafafa
--color=spinner:#0a3a8a,info:#707070
--color=pointer:#0a3a8a,marker:#507020,prompt:#4a2090
