--color=fg:#f8f8f0,bg:#060606,hl:#c0e0ff
--color=fg+:#ffffff,bg+:#303030,hl+:#aad4f8
--color=border:#3b3b39,header:#c0e0ff,gutter:#060606
--color=spinner:#c0e0ff,info:#909090
--color=pointer:#c0e0ff,marker:#c0d880,prompt:#d8c8ff
