--color=fg:#c5c9c5,bg:#181616,hl:#8ba4b0
--color=fg+:#e5e7e5,bg+:#2d4f67,hl+:#7aa89f
--color=border:#3e3d3c,header:#8ba4b0,gutter:#181616
--color=spinner:#8ba4b0,info:#737c73
--color=pointer:#8ba4b0,marker:#8a9a7b,prompt:#a292a3
