--color=fg:#dcd7ba,bg:#1f1f28,hl:#7e9cd8
--color=fg+:#f1efe3,bg+:#2d4f67,hl+:#7aa89f
--color=border:#494748,header:#7e9cd8,gutter:#1f1f28
--color=spinner:#7e9cd8,info:#727169
--color=pointer:#7e9cd8,marker:#76946a,prompt:#957fb8
