--color=fg:#c5c9c7,bg:#090e13,hl:#8ea4a2
--color=fg+:#e5e7e6,bg+:#22262d,hl+:#7aa89f
--color=border:#32373b,header:#8ea4a2,gutter:#090e13
--color=spinner:#8ea4a2,info:#5c6066
--color=pointer:#8ea4a2,marker:#8a9a7b,prompt:#a292a3
