--color=fg:#22262d,bg:#f2f1ef,hl:#597b75
--color=fg+:#08090a,bg+:#e2e1df,hl+:#5e857a
--color=border:#c4c4c4,header:#597b75,gutter:#f2f1ef
--color=spinner:#597b75,info:#5c6066
--color=pointer:#597b75,marker:#6f894e,prompt:#b35b79
