--color=fg:#bebebe,bg:#121212,hl:#f59e0b
--color=fg+:#dddddd,bg+:#333333,hl+:#eaeaea
--color=border:#383838,header:#f59e0b,gutter:#121212
--color=spinner:#f59e0b,info:#8a8a8d
--color=pointer:#f59e0b,marker:#ffc107,prompt:#d35f5f
