--color=fg:#f0e4c5,bg:#1c1b19,hl:#d4bd99
--color=fg+:#fdfbf6,bg+:#45413a,hl+:#e7c07c
--color=border:#4b473f,header:#d4bd99,gutter:#1c1b19
--color=spinner:#d4bd99,info:#706a61
--color=pointer:#d4bd99,marker:#a89984,prompt:#afa499
