--color=fg:#4d4b65,bg:#f7f7f7,hl:#174c97
--color=fg+:#323142,bg+:#d3d3d4,hl+:#f73e7c
--color=border:#d2d1d7,header:#174c97,gutter:#f7f7f7
--color=spinner:#174c97,info:#8e8e91
--color=pointer:#174c97,marker:#598c15,prompt:#bf386e
