--color=fg:#c9c7cd,bg:#161617,hl:#aca1cf
--color=fg+:#e8e7ea,bg+:#2a2a2d,hl+:#f591b2
--color=border:#3d3d3f,header:#aca1cf,gutter:#161617
--color=spinner:#aca1cf,info:#757581
--color=pointer:#aca1cf,marker:#90b99f,prompt:#e29eca
