--color=fg:#cdcecf,bg:#192330,hl:#63cdcf
--color=fg+:#eceded,bg+:#d6d6d7,hl+:#7ad5d6
--color=border:#414953,header:#63cdcf,gutter:#192330
--color=spinner:#63cdcf,info:#39506d
--color=pointer:#63cdcf,marker:#81b29a,prompt:#9d79d6
