--color=fg:#e0e1e4,bg:#101010,hl:#88afa2
--color=fg+:#ffffff,bg+:#696d79,hl+:#88afa2
--color=border:#3e3e3f,header:#88afa2,gutter:#101010
--color=spinner:#88afa2,info:#727272
--color=pointer:#88afa2,marker:#90a959,prompt:#aa759f
