--color=fg:#151515,bg:#e1e1e1,hl:#3e5f66
--color=fg+:#000000,bg+:#c6d5de,hl+:#99ab93
--color=border:#b4b4b4,header:#3e5f66,gutter:#e1e1e1
--color=spinner:#3e5f66,info:#2b2b2b
--color=pointer:#3e5f66,marker:#677940,prompt:#aa759f
