--color=fg:#cbbec2,bg:#322a2d,hl:#49d6e9
--color=fg+:#e6e0e2,bg+:#4a3339,hl+:#60dbeb
--color=border:#544b4e,header:#49d6e9,gutter:#322a2d
--color=spinner:#49d6e9,info:#8b747c
--color=pointer:#49d6e9,marker:#49e9a6,prompt:#df769b
