--color=fg:#005661,bg:#f4f6f6,hl:#00bdd6
--color=fg+:#002024,bg+:#d9e0e0,hl+:#00cbe6
--color=border:#bed3d5,header:#00bdd6,gutter:#f4f6f6
--color=spinner:#00bdd6,info:#8ca6a6
--color=pointer:#00bdd6,marker:#00b368,prompt:#ff5792
