--color=fg:#0c006b,bg:#f2f1f8,hl:#00bdd6
--color=fg+:#05002e,bg+:#d5d3e5,hl+:#00cbe6
--color=border:#bfbcd9,header:#00bdd6,gutter:#f2f1f8
--color=spinner:#00bdd6,info:#9995b7
--color=pointer:#00bdd6,marker:#00b368,prompt:#ff5792
