--color=fg:#becfda,bg:#07273b,hl:#49d6e9
--color=fg+:#e6ecf0,bg+:#103850,hl+:#60dbeb
--color=border:#2f4c5e,header:#49d6e9,gutter:#07273b
--color=spinner:#49d6e9,info:#5988a6
--color=pointer:#49d6e9,marker:#49e9a6,prompt:#df769b
