--color=fg:#ccbfd9,bg:#30243d,hl:#49d6e9
--color=fg+:#ebe6ef,bg+:#3e3352,hl+:#60dbeb
--color=border:#52465f,header:#49d6e9,gutter:#30243d
--color=spinner:#49d6e9,info:#7f659a
--color=pointer:#49d6e9,marker:#49e9a6,prompt:#df769b
