--color=fg:#c5c2d6,bg:#292640,hl:#49d6e9
--color=fg+:#e8e7ee,bg+:#35325a,hl+:#60dbeb
--color=border:#4b4861,header:#49d6e9,gutter:#292640
--color=spinner:#49d6e9,info:#716c93
--color=pointer:#49d6e9,marker:#49e9a6,prompt:#df769b
