--color=fg:#c5cdd3,bg:#1b2932,hl:#72b7c0
--color=fg+:#e8ebed,bg+:#263c4a,hl+:#84c0c8
--color=border:#404d55,header:#72b7c0,gutter:#1b2932
--color=spinner:#72b7c0,info:#5e7887
--color=pointer:#72b7c0,marker:#72c09f,prompt:#c28097
