--color=fg:#b2cacd,bg:#052529,hl:#49d6e9
--color=fg+:#d7e4e5,bg+:#0f3a3f,hl+:#60dbeb
--color=border:#2b494d,header:#49d6e9,gutter:#052529
--color=spinner:#49d6e9,info:#5b858b
--color=pointer:#49d6e9,marker:#49e9a6,prompt:#df769b
