--color=fg:#d8dee9,bg:#2e3440,hl:#81a1c1
--color=fg+:#ffffff,bg+:#3f4758,hl+:#8fbcbb
--color=border:#535965,header:#81a1c1,gutter:#2e3440
--color=spinner:#81a1c1,info:#616e88
--color=pointer:#81a1c1,marker:#a3be8c,prompt:#b48ead
