--color=fg:#d8dee9,bg:#212121,hl:#88c0d0
--color=fg+:#ffffff,bg+:#373839,hl+:#8fbcbb
--color=border:#494b4d,header:#88c0d0,gutter:#212121
--color=spinner:#88c0d0,info:#4c566a
--color=pointer:#88c0d0,marker:#a3be8c,prompt:#b48ead
