--color=fg:#cdcecf,bg:#2e3440,hl:#88c0d0
--color=fg+:#eceded,bg+:#c7cdd9,hl+:#93ccdc
--color=border:#51565f,header:#88c0d0,gutter:#2e3440
--color=spinner:#88c0d0,info:#5a657d
--color=pointer:#88c0d0,marker:#a3be8c,prompt:#b48ead
