--color=fg:#d6d1c9,bg:#292b31,hl:#bda07f
--color=fg+:#f0efec,bg+:#554e48,hl+:#c7c0b5
--color=border:#4f5052,header:#bda07f,gutter:#292b31
--color=spinner:#bda07f,info:#b4ab99
--color=pointer:#bda07f,marker:#76856a,prompt:#b7a593
