--color=fg:#f6dcac,bg:#00172e,hl:#faa968
--color=fg+:#fcf3e3,bg+:#0a3a45,hl+:#a3ccc6
--color=border:#36424a,header:#faa968,gutter:#00172e
--color=spinner:#faa968,info:#134e5a
--color=pointer:#faa968,marker:#028391,prompt:#3f8f8a
