--color=fg:#e6d9db,bg:#2c2525,hl:#f38d70
--color=fg+:#fefefe,bg+:#403e41,hl+:#9bf1e1
--color=border:#554d4d,header:#f38d70,gutter:#2c2525
--color=spinner:#f38d70,info:#72696a
--color=pointer:#f38d70,marker:#adda78,prompt:#a8a9eb
