--color=fg:#e0def4,bg:#191724,hl:#31748f
--color=fg+:#ffffff,bg+:#403d52,hl+:#ebbcba
--color=border:#454352,header:#31748f,gutter:#191724
--color=spinner:#31748f,info:#6e6a86
--color=pointer:#31748f,marker:#31748f,prompt:#c4a7e7
