--color=fg:#a2a3aa,bg:#17182b,hl:#c6797e
--color=fg+:#c2c3c7,bg+:#2b3d47,hl+:#abcbd3
--color=border:#363747,header:#c6797e,gutter:#17182b
--color=spinner:#c6797e,info:#676775
--color=pointer:#c6797e,marker:#969e92,prompt:#4c4e78
