--color=fg:#e6eaea,bg:#152528,hl:#a1cdd8
--color=fg+:#ffffff,bg+:#eaeeee,hl+:#afd4de
--color=border:#435053,header:#a1cdd8,gutter:#152528
--color=spinner:#a1cdd8,info:#2d4f56
--color=pointer:#a1cdd8,marker:#7aa4a1,prompt:#ad5c7c
