--color=fg:#c0caf5,bg:#24283b,hl:#7aa2f7
--color=fg+:#f5f7fd,bg+:#423454,hl+:#7dcfff
--color=border:#464c64,header:#7aa2f7,gutter:#24283b
--color=spinner:#7aa2f7,info:#565f89
--color=pointer:#7aa2f7,marker:#9ece6a,prompt:#bb9af7
