--color=fg:#c0caf5,bg:#1a1b26,hl:#7aa2f7
--color=fg+:#f5f7fd,bg+:#3b2b44,hl+:#7dcfff
--color=border:#3f4254,header:#7aa2f7,gutter:#1a1b26
--color=spinner:#7aa2f7,info:#565f89
--color=pointer:#7aa2f7,marker:#9ece6a,prompt:#bb9af7
