--color=fg:#c8d3f5,bg:#222436,hl:#82aaff
--color=fg+:#fcfcfe,bg+:#413150,hl+:#86e1fc
--color=border:#474a60,header:#82aaff,gutter:#222436
--color=spinner:#82aaff,info:#636da6
--color=pointer:#82aaff,marker:#c3e88d,prompt:#c099ff
