--color=fg:#3760bf,bg:#e1e2e7,hl:#2e7de9
--color=fg+:#264793,bg+:#d0c0d4,hl+:#007197
--color=border:#bcc5de,header:#2e7de9,gutter:#e1e2e7
--color=spinner:#2e7de9,info:#848cb5
--color=pointer:#2e7de9,marker:#587539,prompt:#9854f1
