--color=fg:#c5c8c6,bg:#1d1f21,hl:#8abeb7
--color=fg+:#e4e6e5,bg+:#373b41,hl+:#8abeb7
--color=border:#424445,header:#8abeb7,gutter:#1d1f21
--color=spinner:#8abeb7,info:#969896
--color=pointer:#8abeb7,marker:#b5bd68,prompt:#b294bb
