--color=fg:#4d4d4c,bg:#ffffff,hl:#3e999f
--color=fg+:#2e2e2e,bg+:#d6d6d6,hl+:#3e999f
--color=border:#d8d8d8,header:#3e999f,gutter:#ffffff
--color=spinner:#3e999f,info:#8e908c
--color=pointer:#3e999f,marker:#718c00,prompt:#8959a8
