--color=fg:#eaeaea,bg:#000000,hl:#70c0b1
--color=fg+:#ffffff,bg+:#424242,hl+:#70c0b1
--color=border:#333333,header:#70c0b1,gutter:#000000
--color=spinner:#70c0b1,info:#969896
--color=pointer:#70c0b1,marker:#b9ca4a,prompt:#c397d8
