--color=fg:#ffffff,bg:#002451,hl:#99ffff
--color=fg+:#ffffff,bg+:#003f8e,hl+:#99ffff
--color=border:#385477,header:#99ffff,gutter:#002451
--color=spinner:#99ffff,info:#7285b7
--color=pointer:#99ffff,marker:#d1f1a9,prompt:#ebbbff
