--color=fg:#cccccc,bg:#2d2d2d,hl:#66cccc
--color=fg+:#ebebeb,bg+:#515151,hl+:#66cccc
--color=border:#505050,header:#66cccc,gutter:#2d2d2d
--color=spinner:#66cccc,info:#999999
--color=pointer:#66cccc,marker:#99cc99,prompt:#cc99cc
