--color=fg:#d1d5db,bg:#111827,hl:#bae6fd
--color=fg+:#f3f4f6,bg+:#374151,hl+:#ddd6fe
--color=border:#3b424f,header:#bae6fd,gutter:#111827
--color=spinner:#bae6fd,info:#6b7280
--color=pointer:#bae6fd,marker:#b1e3ad,prompt:#957fb8
