--color=fg:#d1d5db,bg:#1c1c1c,hl:#acd5fc
--color=fg+:#f3f4f6,bg+:#444444,hl+:#d7d7ff
--color=border:#444546,header:#acd5fc,gutter:#1c1c1c
--color=spinner:#acd5fc,info:#767676
--color=pointer:#acd5fc,marker:#afd7af,prompt:#b5b5ff
