--color=fg:#ffffff,bg:#101010,hl:#ea83a5
--color=fg+:#ffffff,bg+:#313131,hl+:#f591b2
--color=border:#454545,header:#ea83a5,gutter:#101010
--color=spinner:#ea83a5,info:#8b8b8b
--color=pointer:#ea83a5,marker:#90b99f,prompt:#e29eca
