--color=fg:#0c0c14,bg:#dedbc8,hl:#005c32
--color=fg+:#000000,bg+:#c4c1ac,hl+:#3b3b3b
--color=border:#b0ada0,header:#005c32,gutter:#dedbc8
--color=spinner:#005c32,info:#645c4b
--color=pointer:#005c32,marker:#005c32,prompt:#762b2f
